version: '2'
services:
  sonarr:
    image: linuxserver/sonarr:4.0.1
    container_name: sonarr
    restart: unless-stopped
    environment:
      - TZ=Europe/London # Specify a timezone to use
      - PUID=1000 # User ID to run as
      - PGID=1000 # Group ID to run as
    volumes:
      - /home/anomy/sonarr/series:/data # Location of all your media
      - /home/anomy/sonarr/config:/config # Contains all relevant configuration files.
    ports:
      - 8989:8989/tcp # Web UI
