---
services:
  radarr:
    image: lscr.io/linuxserver/radarr:latest
    container_name: radarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    volumes:
      - /home/anomy/radarr/config:/config
      - /home/anomy/data/complete:/data
    ports:
      - 7878:7878
    restart: unless-stopped
