version: '3.5'
services:
  jellyfin:
    image: jellyfin/jellyfin
    container_name: jellyfin
    network_mode: 'host'
    volumes:
      - /home/anomy/.jellyfin/cache:/cache
      - /home/anomy/.jellyfin/config:/config
      - /mnt/sda:/media
      - /data/media:/torrent
    restart: 'unless-stopped'
    extra_hosts:
      - "host.docker.internal:host-gateway"
