version: '3.5'
services:
  jellyfin:
    image: jellyfin/jellyfin
    container_name: jellyfin
    user: 115:122
    network_mode: 'host'
    volumes:
      - /home/anomy/containers/jellyfin/config:/config
      - /home/anomy/containers/jellyfin/cache:/cache
    restart: 'unless-stopped'
    extra_hosts:
      - "host.docker.internal:host-gateway"
